#log
logging:
  path: D:\\logs\\study-cloud\\payment-consumer

#
server:
  port: 8087

spring:
  application:
    name: payment-consumer
  cloud:
    nacos:
      config:
        file-extension: yaml
        server-addr: 127.0.0.1:8848
#      discovery:
#        server-addr: 127.0.0.1:8848

#dubbo

dubbo:
  metadata-report:
    address: nacos://127.0.0.1:8848
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20880
  consumer:
    check: false

