#log
logging:
  file:
    path: D:/logs/springboot-demo/consumer
  logback:
    rollingpolicy:
      max-history: 10
#
server:
  port: 8087

#dubbo
dubbo:
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  application:
    name: consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  consumer:
    check: false
    filter: dubboBusinessFilter
